wechat:
  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: C:\zjf\code\github\best-pay-demo\src\main\resources\h5.p12
  notifyUrl: http://www.imooc.com